name: Java CI

on: [ push ]

jobs:
  build:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 14
      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle
      - name: Testing
        run: ./gradlew test
      - name: Building and linting
        run: ./gradlew build --exclude-task test
      - name: Increment Semantiv Version
        run: |
          ./gradlew grabverRelease
          git config --global user.name 'Github'
          git config --global user.email 'boginw@users.noreply.github.com'
          git commit -am "Increment Semantic Version [skip ci]"
          git push
      - name: Publish to the Maven Central Repository
        run: ./gradlew publish
        env:
          MVN_USERNAME_GITHUB: ${{ secrets.MVN_USERNAME_GITHUB }}
          MVN_TOKEN_GITHUB: ${{ secrets.MVN_TOKEN_GITHUB }}
